# Generated by Django 5.2 on 2025-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature_type', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], max_length=10)),
                ('weather_tags', models.TextField(help_text='مثلاً: گرم، سرد، مرطوب')),
            ],
        ),
    ]
