# Generated by Django 5.2 on 2025-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='temperature_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=10),
        ),
    ]
