# Generated by Django 5.2 on 2025-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_drink_temperature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.TextField(default='توضیحی وارد نشده است'),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/'),
        ),
        migrations.AddField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
