# Generated by Django 5.2 on 2025-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
